DOCUMENT_ROOT = 'static'
INDEX_PATH = 'index.html'


PROTOCOL = 'HTTP/1.1'
SERVER_NAME = 'TCPServer (Ruby/2.3.0/2015-12-25)'
CONNECTION_TOKEN = 'close'
HTTP_DATE_FORMAT = '%a, %d %b %Y %H:%M:%S GMT'


ALLOW_METHODS = ['GET', 'HEAD'].join(', ')


STATUS_OK = 200
STATUS_FORBIDDEN = 403
STATUS_NOT_FOUND = 404
STATUS_METHOD_NOT_ALLOWED = 405
STATUS_NOT_IMPLEMENTED = 501


STATUS_VALUE = {
	STATUS_OK: 'OK',
	STATUS_FORBIDDEN: 'Forbidden',
	STATUS_NOT_FOUND: 'Not Found',
	STATUS_METHOD_NOT_ALLOWED: 'Method Not Allowed',
	STATUS_NOT_IMPLEMENTED: 'Not Implemented'
}


FILE_CHUNK_SIZE = 1024 * 1024 * 10
